name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set CDK Parameters
        run: |
          echo "AWS_CDK_MY_PARAMETER=qb-cdk" >> $GITHUB_ENV

      - name: NPM packages
        run: |
          npm install

      - name: Installing AWS CLI
        run: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
              
      - name: Installing cdk 
        run: |
          npm install -g aws-cdk

      - name: cdk build
        run: |
          npm run build

      - name: cdk deploy
        run: |
          cdk deploy