name: CDK Deploy

on:
  push:
    branches:
      - cdk-s3

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STACK_NAME: ${{ secrets.STACK_NAME }}
      PARAMETER_STORE_KEY: ${{ secrets.PARAMETER_STORE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Retrieve Parameter Store Value
        id: parameter-store
        run: |
          PARAMETER_VALUE=$(aws ssm get-parameter --name ${{ env.PARAMETER_STORE_KEY }} --query Parameter.Value --output text)
          echo "PARAMETER_VALUE=$PARAMETER_VALUE" >> $GITHUB_ENV

      - name: NPM packages
        run: |
          npm install

      - name: Install CDK
        run:  | 
          npm install -g aws-cdk

      - name: Install dependancy
        run: | 
          npm install ts-node
      
      - name: Build command
        run: | 
          npm run build

      - name: deploy CDK Stack
        run: |
          cdk deploy --require-approval never --context parameterValue= ${{env.PARAMETER_VALUE }}